title: Association 404
email: your-email@example.com
description: Association des élèves du CFPT informatique
baseurl: "/"
url: "https://404.gg"
repo: "nicolapps/404-demo" # GitHub repository name used for the “Edit” link

# Event banner settings
eventbanner:
  show: false
  text: Assemblée générale le lundi 31 février !
  url: "/blog/2018/12/02/bienvenue-sur-notre-nouveau-site.html"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  proces-verbaux:
    permalink: /proces-verbaux/:path
    output: true

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .editorconfig
